### ISSUE TITLE
What parameters do I need to change if I want to delete the solvent faster

### ISSUE THREAD

**Issue by kkivg** [ATB-UQ/PyThinFilm#10]
What parameters do I need to change if I want to delete the solvent faster
I ran a 10ns MD test case and couldn't see the process of solvent removal

**Comment by kkivg** [comment]
The main operating parameters used in the src/PyThinFilm/test/solvent_accel_test.yml

**Comment by ssande7** [comment]
The deposition_log files will tell you about solvent removal (which region it happened in, how many molecules were deleted, etc). Removal should normally be slow to avoid artificially changing the density profile of the surface film.

The solvent removal rate is `number` / `run_time`, so you can increase `number` (in the `solvent_delete` section) to delete more solvent molecules per cycle. Depending on the volume of the region you delete from, you may also need to reduce `min_separation` (otherwise it will stop trying if it can't find sufficiently distant molecules to delete).

You should be careful with both of these settings though to make sure you don't create a region with artificially low solvent content.
